---
title: "iteration_functions"
author: "Caleigh Dwyer"
date: "2023-10-26"
output: html_document
---

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
library(rvest)

library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


```{r}
set.seed(12345)

##this ensures that every time you get random numbers, it uses the same set of random numbers
```


## Z score function
z scores subtract the mean and divide by the sd

```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```

compute z scores for x_vec

```{r}
(x_vec - mean(x_vec))/sd(x_vec)

```

write this as a function to be applied to other vectors:

```{r}
z_score = function(x){
  
  z= (x-mean(x))/sd(x)
  
  z
}
```


```{r}
z_score(x=x_vec)

# this runs the function we just made

z_score(x = rnorm(10, mean = 5))
```


Keep checking

```{r}
z_score(x = 3)

z_score(c("my", "name", "is", "jeff"))

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris)

##none of these work, for various reasons. you can't run it on characters
```

Change the function

```{r}
z_score = function(x){
  
  if(!is.numeric(x)){
    stop("Argument should be numbers")
  } else if (length(x)<2){
    stop("You need at least 2 numbers to get z scores")
  }
  z= (x-mean(x))/sd(x)
  
  z
}
```


let's try again:

```{r}
z_score(x = 3)

z_score(c("my", "name", "is", "jeff"))

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris)

##none of these work, but now our output tells us why this doesn't work because we've used conditional statements that explicitly name the requirements
```



